const quotes = [
  "Progress over perfection.",
  "Discipline beats motivation.",
  "Tiny steps, massive change.",
  "You don’t need permission to begin.",
  "Show up, even when it’s hard.",
  "Done is better than perfect.",
  "Build momentum, not excuses.",
  "Your future self is watching.",
  "Start messy. Refine later.",
  "Focus is a superpower.",
  "Consistency creates miracles.",
  "Be patient with the process.",
  "Dreams demand discipline.",
  "Make it a habit, not a wish.",
  "Create before you consume.",
  "Courage over comfort.",
  "Less noise, more work.",
  "One chapter at a time.",
  "Reps over results.",
  "The day you start is the day you change.",
  "Better small progress than big regret.",
  "Invest in your skills daily.",
  "Silence the doubt with action.",
  "Your pace is your power.",
  "Direction beats speed.",
  "Clarity loves simplicity.",
  "Protect your focus.",
  "No shortcuts, just steps.",
  "Turn pressure into performance.",
  "Confidence follows commitment.",
  "Build a life you don’t need to escape from.",
  "Energy flows where attention goes.",
  "Keep the promise you made to yourself.",
  "Hard now, easy later.",
  "You become what you repeat.",
  "Don’t wait. Create.",
  "Start where you are; use what you have.",
  "You can do hard things.",
  "Mindset first, mechanics second.",
  "Be consistent enough to be inevitable.",
  "Make your habits your home.",
  "Show your work.",
  "Win the morning, win the day.",
  "Talent starts the race; discipline finishes it.",
  "Less talking, more doing.",
  "The comeback is built in silence.",
  "No one is coming. It’s on you.",
  "Stack small wins.",
  "If it matters, schedule it.",
  "Your actions teach your mind.",
  "Plant the seeds, trust the season.",
  "Work until it looks effortless.",
  "Train your attention.",
  "Make it simple. Make it yours.",
  "Effort compounds.",
  "Stay curious, stay kind, stay consistent.",
  "Let your habits speak.",
  "Be the proof.",
  "Your standard is your ceiling.",
  "Direction over distraction.",
  "Quiet progress is still progress.",
  "Replace fear with reps.",
  "Write your own definition of success.",
  "Protect your mornings.",
  "Build what you wish existed.",
  "Practice makes permanent.",
  "Keep moving. The path appears.",
  "Results follow routines.",
  "Every day is day one.",
  "Start small. Stay steady.",
  "Turn doubt into data.",
  "Make time, don’t find it.",
  "Craft your character.",
  "Less scrolling, more building.",
  "Simplicity scales.",
  "Do it for the story you’ll tell.",
  "Your habits are voting for your future.",
  "Be known for your consistency.",
  "Make your future non-negotiable.",
  "Hard choices, easy life.",
  "The work will teach you.",
  "Direction is a decision.",
  "Make your standards visible.",
  "Show up like it’s already yours.",
  "Seek progress, not permission.",
  "Your focus creates your fate.",
  "Say no to stay noble.",
  "Keep promises. Build pride.",
  "Build your resilience reps.",
  "Protect the work from the world.",
  "Be useful, then be unique.",
  "Your effort is the algorithm.",
  "Stay low, build slow.",
  "Patience is the price of greatness.",
  "Make your why a habit.",
  "Let your future pull you.",
  "Less wishing, more working.",
  "Listen to your results.",
  "You’re closer than you think.",
  "The grind is the gift.",
  "Keep it simple. Keep it moving.",
  "Make discipline your default.",
  "Design your day, own your life.",
  "Routine is the road to results.",
  "Turn pressure into practice.",
  "Consistency beats intensity.",
  "Be relentless, not reckless.",
  "Chase craft, not clout.",
  "Quiet the noise. Do the work.",
  "You can’t pour from an empty cup.",
  "The habit is the goal.",
  "Create something worth remembering.",
  "Stay steady in the storm.",
  "Every step counts, even small ones.",
  "Discomfort is your growth zone.",
  "Dream, plan, execute, repeat.",
  "Start with intention.",
  "Do it scared.",
  "Clarity kills chaos.",
  "Stay humble, work hard.",
  "Hustle with heart.",
  "Your growth scares your comfort zone.",
  "Fear is temporary, regret is forever.",
  "Less comfort, more courage.",
  "Take the leap, grow the wings.",
  "Build what sets your soul on fire.",
  "Push beyond possible.",
  "Your vibe attracts your tribe.",
  "Every master was once a beginner.",
  "Ideas mean nothing without action.",
  "No zero days.",
  "Success is rented, rent is due daily.",
  "Excuses don’t build empires.",
  "Fall down seven times, stand up eight.",
  "A little progress each day adds up.",
  "Work in silence, let results talk.",
  "Focus on the next step, not the whole staircase.",
  "Choose purpose over popularity.",
  "Lead yourself first.",
  "Your struggle is your strength.",
  "Action cures fear.",
  "Stop wishing, start working.",
  "The best views come from hard climbs.",
  "Persistence breaks resistance.",
  "You don’t find willpower, you create it.",
  "The time will pass anyway, use it well.",
  "Be so consistent it’s boring.",
  "Stay consistent, the magic will come.",
  "Work smart and hard.",
  "Better an oops than a what-if.",
  "Start now, adjust later.",
  "Every win starts with a try.",
  "Comfort zones are cages.",
  "Your habits shape your identity.",
  "Do something your future self will thank you for.",
  "Stay hungry, stay foolish.",
  "Push yourself because no one else will.",
  "Great things take time, stay patient.",
  "Don’t stop until you’re proud.",
  "Your dreams are valid.",
  "Nobody cares, work harder.",
  "Better late than never.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Prove them wrong.",
  "Big things often have small beginnings.",
  "Start where you are.",
  "Be a warrior, not a worrier.",
  "Go the extra mile, it’s never crowded.",
  "A year from now you’ll wish you started today.",
  "Great things never come from comfort zones.",
  "Stay positive, work hard, make it happen.",
  "Fall in love with the process.",
  "Think it. Want it. Get it.",
  "Stop doubting yourself.",
  "Push through the pain.",
  "Your only limit is you.",
  "Work until you no longer have to introduce yourself.",
  "Success is a series of small wins.",
  "Keep showing up.",
  "Don’t call it a dream, call it a plan.",
  "Level up daily.",
  "Your grind will be worth it.",
  "Strive for progress, not perfection.",
  "Do it with passion or not at all.",
  "Wake up with determination.",
  "Don’t be busy, be productive.",
  "Small steps are still steps.",
  "Prove yourself to yourself.",
  "Decide. Commit. Succeed.",
  "Stay focused and never give up.",
  "Hard work opens doors.",
  "Sweat, sacrifice, success.",
  "Failure is the tuition you pay for success.",
  "Show up for yourself.",
  "Believe in your grind.",
  "Wake up and chase it.",
  "Discipline is freedom.",
  "Choose your hard.",
  "Take action and the rest follows.",
  "Be stronger than your excuses.",
  "Push yourself past average.",
  "Results take time—be patient.",
  "Keep going, you’re growing.",
  "Hustle beats luck.",
  "Winners are made, not born.",
  "Your vision, your rules.",
  "Do the work no one sees.",
  "Stay consistent, stay confident.",
  "Focus > motivation.",
  "Outwork your yesterday.",
  "Start small, dream big.",
  "No grind, no glory."
];


const usedIndexs = new Set()
const quoteTag = document.getElementById('text')
function generateQuote() {
  if (usedIndexs.size === quotes.length) {
    quoteTag.innerHTML = "All quotes used!";
    return;
  }

  let randomIdx;
  do {
    randomIdx = Math.floor(Math.random() * quotes.length);
  } while (usedIndexs.has(randomIdx));

  const quote = quotes[randomIdx];
  quoteTag.innerHTML = quote;
  usedIndexs.add(randomIdx);
}